# plugin: aws_ec2
# regions:
#   - us-east-1
# filters:
#   instance-state-name: running

all:
  hosts:
    dev1:
      ansible_host: 54.210.58.252
      ansible_user: ec2-user
      ansible_ssh_private_key_file: /Users/ben/aws/aws_keys/ec2-default.pem
  children:
    aws_ec2:
      hosts:
        dev1:
